package com.kinder.kinder_ielts.constant;

public enum EnumCountry {
    AFGHANISTAN("Afghanistan", "Afghanistan"),
    ALBANIA("Albania", "Albania"),
    ALGERIA("Algeria", "Algerie"),
    ANDORRA("Andorra", "Andorra"),
    ANGOLA("Angola", "Angola"),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda", "Antigua và Barbuda"),
    ARGENTINA("Argentina", "Argentina"),
    ARMENIA("Armenia", "Armenia"),
    AUSTRALIA("Australia", "Úc"),
    AUSTRIA("Austria", "Áo"),
    AZERBAIJAN("Azerbaijan", "Azerbaijan"),
    BAHAMAS("Bahamas", "Bahamas"),
    BAHRAIN("Bahrain", "Bahrain"),
    BANGLADESH("Bangladesh", "Bangladesh"),
    BARBADOS("Barbados", "Barbados"),
    BELARUS("Belarus", "Belarus"),
    BELGIUM("Belgium", "Bỉ"),
    BELIZE("Belize", "Belize"),
    BENIN("Benin", "Benin"),
    BHUTAN("Bhutan", "Bhutan"),
    BOLIVIA("Bolivia", "Bolivia"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina", "Bosnia và Herzegovina"),
    BOTSWANA("Botswana", "Botswana"),
    BRAZIL("Brazil", "Brazil"),
    BRUNEI("Brunei", "Brunei"),
    BULGARIA("Bulgaria", "Bulgaria"),
    BURKINA_FASO("Burkina Faso", "Burkina Faso"),
    BURUNDI("Burundi", "Burundi"),
    CAMBODIA("Cambodia", "Campuchia"),
    CAMEROON("Cameroon", "Cameroon"),
    CANADA("Canada", "Canada"),
    CAPE_VERDE("Cape Verde", "Cabo Verde"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic", "Cộng hòa Trung Phi"),
    CHAD("Chad", "Chad"),
    CHILE("Chile", "Chile"),
    CHINA("China", "Trung Quốc"),
    COLOMBIA("Colombia", "Colombia"),
    COMOROS("Comoros", "Comoros"),
    CONGO("Congo", "Congo"),
    COSTA_RICA("Costa Rica", "Costa Rica"),
    CROATIA("Croatia", "Croatia"),
    CUBA("Cuba", "Cuba"),
    CYPRUS("Cyprus", "Síp"),
    CZECH_REPUBLIC("Czech Republic", "Séc"),
    DENMARK("Denmark", "Đan Mạch"),
    DJIBOUTI("Djibouti", "Djibouti"),
    DOMINICA("Dominica", "Dominica"),
    DOMINICAN_REPUBLIC("Dominican Republic", "Cộng hòa Dominica"),
    ECUADOR("Ecuador", "Ecuador"),
    EGYPT("Egypt", "Ai Cập"),
    EL_SALVADOR("El Salvador", "El Salvador"),
    EQUATORIAL_GUINEA("Equatorial Guinea", "Guinea Xích Đạo"),
    ERITREA("Eritrea", "Eritrea"),
    ESTONIA("Estonia", "Estonia"),
    ESWATINI("Eswatini", "Eswatini"),
    ETHIOPIA("Ethiopia", "Ethiopia"),
    FIJI("Fiji", "Fiji"),
    FINLAND("Finland", "Phần Lan"),
    FRANCE("France", "Pháp"),
    GABON("Gabon", "Gabon"),
    GAMBIA("Gambia", "Gambia"),
    GEORGIA("Georgia", "Georgia"),
    GERMANY("Germany", "Đức"),
    GHANA("Ghana", "Ghana"),
    GREECE("Greece", "Hy Lạp"),
    GRENADA("Grenada", "Grenada"),
    GUATEMALA("Guatemala", "Guatemala"),
    GUINEA("Guinea", "Guinea"),
    GUINEA_BISSAU("Guinea-Bissau", "Guinea-Bissau"),
    GUYANA("Guyana", "Guyana"),
    HAITI("Haiti", "Haiti"),
    HONDURAS("Honduras", "Honduras"),
    HUNGARY("Hungary", "Hungary"),
    ICELAND("Iceland", "Iceland"),
    INDIA("India", "Ấn Độ"),
    INDONESIA("Indonesia", "Indonesia"),
    IRAN("Iran", "Iran"),
    IRAQ("Iraq", "Iraq"),
    IRELAND("Ireland", "Ireland"),
    ISRAEL("Israel", "Israel"),
    ITALY("Italy", "Ý"),
    JAMAICA("Jamaica", "Jamaica"),
    JAPAN("Japan", "Nhật Bản"),
    JORDAN("Jordan", "Jordan"),
    KAZAKHSTAN("Kazakhstan", "Kazakhstan"),
    KENYA("Kenya", "Kenya"),
    KIRIBATI("Kiribati", "Kiribati"),
    KOREA_NORTH("North Korea", "Triều Tiên"),
    KOREA_SOUTH("South Korea", "Hàn Quốc"),
    KOSOVO("Kosovo", "Kosovo"),
    KUWAIT("Kuwait", "Kuwait"),
    KYRGYZSTAN("Kyrgyzstan", "Kyrgyzstan"),
    LAOS("Laos", "Lào"),
    LATVIA("Latvia", "Latvia"),
    LEBANON("Lebanon", "Lebanon"),
    LESOTHO("Lesotho", "Lesotho"),
    LIBERIA("Liberia", "Liberia"),
    LIBYA("Libya", "Libya"),
    LIECHTENSTEIN("Liechtenstein", "Liechtenstein"),
    LITHUANIA("Lithuania", "Lithuania"),
    LUXEMBOURG("Luxembourg", "Luxembourg"),
    MADAGASCAR("Madagascar", "Madagascar"),
    MALAWI("Malawi", "Malawi"),
    MALAYSIA("Malaysia", "Malaysia"),
    MALDIVES("Maldives", "Maldives"),
    MALI("Mali", "Mali"),
    MALTA("Malta", "Malta"),
    MARSHALL_ISLANDS("Marshall Islands", "Quần đảo Marshall"),
    MAURITANIA("Mauritania", "Mauritania"),
    MAURITIUS("Mauritius", "Mauritius"),
    MEXICO("Mexico", "Mexico"),
    MICRONESIA("Micronesia", "Micronesia"),
    MOLDOVA("Moldova", "Moldova"),
    MONACO("Monaco", "Monaco"),
    MONGOLIA("Mongolia", "Mông Cổ"),
    MONTENEGRO("Montenegro", "Montenegro"),
    MOROCCO("Morocco", "Morocco"),
    MOZAMBIQUE("Mozambique", "Mozambique"),
    MYANMAR("Myanmar", "Myanmar"),
    NAMIBIA("Namibia", "Namibia"),
    NAURU("Nauru", "Nauru"),
    NEPAL("Nepal", "Nepal"),
    NETHERLANDS("Netherlands", "Hà Lan"),
    NEW_ZEALAND("New Zealand", "New Zealand"),
    NICARAGUA("Nicaragua", "Nicaragua"),
    NIGER("Niger", "Niger"),
    NIGERIA("Nigeria", "Nigeria"),
    NORTH_MACEDONIA("North Macedonia", "Bắc Macedonia"),
    NORWAY("Norway", "Na Uy"),
    OMAN("Oman", "Oman"),
    PAKISTAN("Pakistan", "Pakistan"),
    PALAU("Palau", "Palau"),
    PALESTINE("Palestine", "Palestine"),
    PANAMA("Panama", "Panama"),
    PAPUA_NEW_GUINEA("Papua New Guinea", "Papua New Guinea"),
    PARAGUAY("Paraguay", "Paraguay"),
    PERU("Peru", "Peru"),
    PHILIPPINES("Philippines", "Philippines"),
    POLAND("Poland", "Ba Lan"),
    PORTUGAL("Portugal", "Bồ Đào Nha"),
    QATAR("Qatar", "Qatar"),
    ROMANIA("Romania", "Romania"),
    RUSSIA("Russia", "Nga"),
    RWANDA("Rwanda", "Rwanda"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis", "Saint Kitts và Nevis"),
    SAINT_LUCIA("Saint Lucia", "Saint Lucia"),
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines", "Saint Vincent và Grenadines"),
    SAMOA("Samoa", "Samoa"),
    SAN_MARINO("San Marino", "San Marino"),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe", "Sao Tome và Principe"),
    SAUDI_ARABIA("Saudi Arabia", "Ả Rập Saudi"),
    SENEGAL("Senegal", "Senegal"),
    SERBIA("Serbia", "Serbia"),
    SEYCHELLES("Seychelles", "Seychelles"),
    SIERRA_LEONE("Sierra Leone", "Sierra Leone"),
    SINGAPORE("Singapore", "Singapore"),
    SLOVAKIA("Slovakia", "Slovakia"),
    SLOVENIA("Slovenia", "Slovenia"),
    SOLOMON_ISLANDS("Solomon Islands", "Quần đảo Solomon"),
    SOMALIA("Somalia", "Somalia"),
    SOUTH_AFRICA("South Africa", "Nam Phi"),
    SOUTH_SUDAN("South Sudan", "Nam Sudan"),
    SPAIN("Spain", "Tây Ban Nha"),
    SRI_LANKA("Sri Lanka", "Sri Lanka"),
    SUDAN("Sudan", "Sudan"),
    SURINAME("Suriname", "Suriname"),
    SWEDEN("Sweden", "Thụy Điển"),
    SWITZERLAND("Switzerland", "Thụy Sĩ"),
    SYRIA("Syria", "Syria"),
    TAJIKISTAN("Tajikistan", "Tajikistan"),
    TANZANIA("Tanzania", "Tanzania"),
    THAILAND("Thailand", "Thái Lan"),
    TIMOR_LESTE("Timor-Leste", "Đông Timor"),
    TOGO("Togo", "Togo"),
    TONGA("Tonga", "Tonga"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago", "Trinidad và Tobago"),
    TUNISIA("Tunisia", "Tunisia"),
    TURKEY("Turkey", "Thổ Nhĩ Kỳ"),
    TURKMENISTAN("Turkmenistan", "Turkmenistan"),
    TUVALU("Tuvalu", "Tuvalu"),
    UGANDA("Uganda", "Uganda"),
    UKRAINE("Ukraine", "Ukraine"),
    UNITED_ARAB_EMIRATES("United Arab Emirates", "Các Tiểu vương quốc Ả Rập Thống nhất"),
    UNITED_KINGDOM("United Kingdom", "Vương quốc Anh"),
    UNITED_STATES("United States", "Hoa Kỳ"),
    URUGUAY("Uruguay", "Uruguay"),
    UZBEKISTAN("Uzbekistan", "Uzbekistan"),
    VANUATU("Vanuatu", "Vanuatu"),
    VATICAN("Vatican", "Vatican"),
    VENEZUELA("Venezuela", "Venezuela"),
    VIETNAM("Vietnam", "Việt Nam"),
    YEMEN("Yemen", "Yemen"),
    ZAMBIA("Zambia", "Zambia"),
    ZIMBABWE("Zimbabwe", "Zimbabwe");

    private final String english;
    private final String vietnamese;

    EnumCountry(String english, String vietnamese) {
        this.english = english;
        this.vietnamese = vietnamese;
    }

    public String getEnglish() {
        return english;
    }

    public String getVietnamese() {
        return vietnamese;
    }
}