name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 # Set up Java, to run Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven # Build the JAR *before* building the Docker image
        run: mvn clean install -DskipTests=true

      - name: Decode and Save Keystore
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > src/main/resources/keystore.p12

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        env:
          IMAGE_NAME: highschoolvn/kinder_ielts
        run: |
          docker build -t ${IMAGE_NAME} .
          docker push ${IMAGE_NAME}

      - name: Set up SSH
        run: |
          # Install SSH client
          sudo apt-get update
          sudo apt-get install -y openssh-client

          # Create SSH directory
          mkdir -p ~/.ssh

          # Write the private key to a file
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

          # Set correct permissions
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H 150.95.109.50 >> ~/.ssh/known_hosts  # 150.95.109.50

      - name: Deploy to VPS
        run: |
          # Add your deployment commands here, using SSH to connect to your VPS
          ssh your_username@150.95.109.50 "
            # Your deployment commands (e.g., stop/start Docker container, git pull, etc.)
            docker stop kinder_ielts && docker rm kinder_ielts && docker rmi highschoolvn/kinder_ielts || true
            docker pull highschoolvn/kinder_ielts
            docker run -d \
              --name kinder_ielts \
              -p 8080:8080 \
              -e SPRING_CONFIG_LOCATION=classpath:/application.properties \
              -e SPRING_DATASOURCE_URL=\"jdbc:sqlserver://150.95.109.50:1433;encrypt=true;trustServerCertificate=true;databaseName=kinder_ielts\" \
              -e SPRING_DATASOURCE_USERNAME=sa \
              -e SPRING_DATASOURCE_PASSWORD=Fpt123123@ \
              -e SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.SQLServerDialect \
              -e SPRING_JPA_HIBERNATE_DDL_AUTO=update \
              -e SPRING_JPA_SHOW_SQL=true \
              -e SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true \
              -e SECRET_KEY=94b83cf0b942b22cc7c98924f90eec3bc90b974d61392b4eb694b85f7c68265e \
              -e EXPIRATION=604800000 \
              -e REFRESH_TOKEN_EXPIRATION=2592000000 \
              -e SERVER_PORT=8080 \
              -e SERVER_SSL_ENABLED=true \
              -e SERVER_SSL_KEY_STORE=file:/app/resources/keystore.p12 \
              -e SERVER_SSL_KEY_STORE_PASSWORD=KinderIelts \
              -e SERVER_SSL_KEY_STORE_TYPE=PKCS12 \
              -e SERVER_SSL_KEY_ALIAS=kinder_ielts \
              -e SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE=Asia/Bangkok \
              -e SPRING_JACKSON_TIME_ZONE=Asia/Bangkok \
              -e AZURE_TENANT_ID=2ced3377-c996-45c8-bf26-d07bd60c5bbc \
              -e AZURE_CLIENT_ID=a2621942-5d1d-4e45-94c4-db26eb7331c5 \
              -e AZURE_CLIENT_SECRET=EV98Q~MjOJYKG4r6kif3IMvUzIewfml1gch1GclN \
              -e ONEDRIVE_DRIVE_ID='b!Lb7664wBnECJaM4v2EeKOSoPmwNkuPFNgAIrg0gVnm-5bK4ObU6pRIa3ZpYmjFEe' \
              highschoolvn/kinder_ielts
            " # Close the SSH command
